ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE TABLESPACE DESARROLLO
DATAFILE '/APP/USER/PRODUCT/21C/ORADATA/XE/DESARROLLO01.dbf'
SIZE 500M
AUTOEXTEND ON
NEXT 100M
MAXSIZE 5G
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;

CREATE USER DESARROLLO
IDENTIFIED BY "PASS"
DEFAULT TABLESPACE DESARROLLO
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON DESARROLLO;

GRANT CONNECT, RESOURCE TO DESARROLLO; -- CONNECT para conectarse, RESOURCE para crear objetos (tablas, etc.)
GRANT
  CREATE SESSION,
  CREATE TABLE,
  CREATE VIEW,
  CREATE SEQUENCE,
  CREATE PROCEDURE,
  CREATE TRIGGER
TO DESARROLLO;
