alter session set "_ORACLE_SCRIPT"=true;

CREATE TABLESPACE DESARROLLO_TS DATAFILE '/APP/DESARROLLO/PRODUCT/21C/ORADATA/XE/DESARROLLO_TS.dbf' SIZE 100M AUTOEXTEND ON;

CREATE USER DESARROLLO IDENTIFIED BY "1234abcd."
DEFAULT TABLESPACE DESARROLLO_TS
ACCOUNT UNLOCK;

GRANT CONNECT, RESOURCE TO DESARROLLO; -- CONNECT para conectarse, RESOURCE para crear objetos (tablas, etc.)
GRANT DBA TO DESARROLLO;